version: '3.8'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    ports:
      - "8008"
    volumes:
      - synapse_data:/data
      - ./homeserver.yaml:/data/homeserver.yaml:ro
      - ./log.config:/data/log.config:ro
    depends_on:
      - postgres
      - redis
    labels:
      - homepage.group=Synapse
      - homepage.name=Synapse App
      - homepage.icon=mdi-video-wireless-outline
      - homepage.href=https://matrix.dartungar.com/

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_DB=synapse
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    labels:
      - homepage.group=Synapse
      - homepage.name=Synapse DB
      - homepage.icon=mdi-video-wireless-outline
      - homepage.href=https://matrix.dartungar.com/


  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    labels:
      - homepage.group=Synapse
      - homepage.name=Synapse Redis
      - homepage.icon=mdi-video-wireless-outline
      - homepage.href=https://matrix.dartungar.com/


  coturn:
    image: coturn/coturn:latest
    restart: unless-stopped
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf:ro
    environment:
      - EXTERNAL_IP=${VPS_PUBLIC_IP}
    labels:
      - homepage.group=Synapse
      - homepage.name=Synapse Coturn
      - homepage.icon=mdi-video-wireless-outline
      - homepage.href=https://matrix.dartungar.com/


volumes:
  synapse_data:
  postgres_data:
  redis_data: